### ISSUE TITLE
★ Roadmap

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/canvas#74]
This is a roadmap of future plans with `canvas`, the intention is to finish all these matters, but not necessarily in a timely matter. Please see this list as possible plans. Features will be implemented in the `develop` branch and merged when deemed mature.

- [x] Parse SFNT (TTF and OTF) fonts with tables cmap, head, hhea, hmtx, maxp, name, OS/2, post, glyf, loca
- [x] Generate subset font by defining the glyph IDs that are used
- [x] Parse extra tables: kern, vhea, vmtx
- [ ] Parse GPOS, GSUB, and GDEF tables for shaping in SVGs
- [ ] Parse CFF, CFF2, gasp, JSTF, SVG, and other tables
- [ ] What happens if `ToUnicode` for a glyphID doesn't exist? (PDF)
- [x] Text shaping using HarfBuzz (https://harfbuzz.github.io/ch01s03.html) to properly display Arabic, Devanagari, etc.
- [x] Text directionality using FriBidi (https://github.com/fribidi/fribidi) in order to mix e.g. Arabic and English in one sentence
- [x] Vertical text such as Chinese and Japanese
- [ ] Font features and variants to enable swash or stylistic ligatures, and to change the font weight variably
- [x] Text justification algorithm from Donald Knuth (http://www.eprg.org/G53DOC/pdfs/knuth-plass-breaking.pdf) as used in TeX
- [ ] Text itemization using a rich text implementation to allow different font faces and decoration to occur in one paragraph
- [ ] Support adding paths and images to rich text implementation for e.g. emoticons
- [ ] Make PDFs linearized (see Annex F) if possible
- [ ] Implement `Layout` to organize elements vertically/horizontally or like CSS's flexbox
- [ ] Support fill patterns (from paths?) and gradients (linear, radial)
- [ ] Support different `Context` for other types of coordinate systems, such as radial or perspective
- [ ] Support path intersection to allow path merging (AND, OR, XOR)
- [ ] Set Z-index for draw order for `Canvas`
- [ ] `SetView` should also change coordinate position
- [ ] Improve examples
- [ ] Improve readme
